//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pizza
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pizza()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int PizzaId { get; set; }
        public int CheeseId { get; set; }
        public int SauceId { get; set; }
        public int SizeId { get; set; }
        public Nullable<int> ToppingId { get; set; }
        public Nullable<int> CrustId { get; set; }
        public int OrderId { get; set; }
        public decimal Price { get; set; }
    
        public virtual Cheese Cheese { get; set; }
        public virtual Crust Crust { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        public virtual Order Order { get; set; }
        public virtual Sauce Sauce { get; set; }
        public virtual Size Size { get; set; }
        public virtual Topping Topping { get; set; }
    }
}
